<?php

/**
 * ContentRecommendationLinkTier.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Sync Core.
 *
 * The Sync Core that sends and receives content from all connected sites and services for Content Sync.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdgeBox\SyncCore\V2\Raw\Model;

/**
 * ContentRecommendationLinkTier Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class ContentRecommendationLinkTier
{
    /**
     * Possible values of this enum.
     */
    public const _500_CITED_STATEMENT = '500-cited-statement';

    public const _400_CITED_ANSWER = '400-cited-answer';

    public const _300_TOPICAL = '300-topical';

    public const _200_PROMPT_INTENT = '200-prompt-intent';

    public const _100_UNLINKED = '100-unlinked';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_500_CITED_STATEMENT,
            self::_400_CITED_ANSWER,
            self::_300_TOPICAL,
            self::_200_PROMPT_INTENT,
            self::_100_UNLINKED,
        ];
    }
}
