<?php

/**
 * ContentExtractions.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Sync Core.
 *
 * The Sync Core that sends and receives content from all connected sites and services for Content Sync.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdgeBox\SyncCore\V2\Raw\Model;

use EdgeBox\SyncCore\V2\Raw\ObjectSerializer;

/**
 * ContentExtractions Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class ContentExtractions implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ContentExtractions';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'htmlDom' => 'ContentExtractionDescriptor',
        'systemPage' => 'ContentExtractionDescriptor',
        'textMarkdown' => 'ContentExtractionDescriptor',
        'imageDescription' => 'ContentExtractionDescriptor',
        'contentSnapshot' => 'ContentExtractionDescriptor',
        'contentSnapshotDelta' => 'ContentExtractionDescriptor',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'htmlDom' => null,
        'systemPage' => null,
        'textMarkdown' => null,
        'imageDescription' => null,
        'contentSnapshot' => null,
        'contentSnapshotDelta' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'htmlDom' => true,
        'systemPage' => true,
        'textMarkdown' => true,
        'imageDescription' => true,
        'contentSnapshot' => true,
        'contentSnapshotDelta' => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'htmlDom' => 'html_dom',
        'systemPage' => 'system_page',
        'textMarkdown' => 'text_markdown',
        'imageDescription' => 'image_description',
        'contentSnapshot' => 'content_snapshot',
        'contentSnapshotDelta' => 'content_snapshot_delta',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'htmlDom' => 'setHtmlDom',
        'systemPage' => 'setSystemPage',
        'textMarkdown' => 'setTextMarkdown',
        'imageDescription' => 'setImageDescription',
        'contentSnapshot' => 'setContentSnapshot',
        'contentSnapshotDelta' => 'setContentSnapshotDelta',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'htmlDom' => 'getHtmlDom',
        'systemPage' => 'getSystemPage',
        'textMarkdown' => 'getTextMarkdown',
        'imageDescription' => 'getImageDescription',
        'contentSnapshot' => 'getContentSnapshot',
        'contentSnapshotDelta' => 'getContentSnapshotDelta',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('htmlDom', $data ?? [], null);
        $this->setIfExists('systemPage', $data ?? [], null);
        $this->setIfExists('textMarkdown', $data ?? [], null);
        $this->setIfExists('imageDescription', $data ?? [], null);
        $this->setIfExists('contentSnapshot', $data ?? [], null);
        $this->setIfExists('contentSnapshotDelta', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets htmlDom.
     *
     * @return null|ContentExtractionDescriptor
     */
    public function getHtmlDom()
    {
        return $this->container['htmlDom'];
    }

    /**
     * Sets htmlDom.
     *
     * @param null|ContentExtractionDescriptor $htmlDom htmlDom
     *
     * @return self
     */
    public function setHtmlDom($htmlDom)
    {
        if (is_null($htmlDom)) {
            array_push($this->openAPINullablesSetToNull, 'htmlDom');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('htmlDom', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['htmlDom'] = $htmlDom;

        return $this;
    }

    /**
     * Gets systemPage.
     *
     * @return null|ContentExtractionDescriptor
     */
    public function getSystemPage()
    {
        return $this->container['systemPage'];
    }

    /**
     * Sets systemPage.
     *
     * @param null|ContentExtractionDescriptor $systemPage systemPage
     *
     * @return self
     */
    public function setSystemPage($systemPage)
    {
        if (is_null($systemPage)) {
            array_push($this->openAPINullablesSetToNull, 'systemPage');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('systemPage', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['systemPage'] = $systemPage;

        return $this;
    }

    /**
     * Gets textMarkdown.
     *
     * @return null|ContentExtractionDescriptor
     */
    public function getTextMarkdown()
    {
        return $this->container['textMarkdown'];
    }

    /**
     * Sets textMarkdown.
     *
     * @param null|ContentExtractionDescriptor $textMarkdown textMarkdown
     *
     * @return self
     */
    public function setTextMarkdown($textMarkdown)
    {
        if (is_null($textMarkdown)) {
            array_push($this->openAPINullablesSetToNull, 'textMarkdown');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('textMarkdown', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['textMarkdown'] = $textMarkdown;

        return $this;
    }

    /**
     * Gets imageDescription.
     *
     * @return null|ContentExtractionDescriptor
     */
    public function getImageDescription()
    {
        return $this->container['imageDescription'];
    }

    /**
     * Sets imageDescription.
     *
     * @param null|ContentExtractionDescriptor $imageDescription imageDescription
     *
     * @return self
     */
    public function setImageDescription($imageDescription)
    {
        if (is_null($imageDescription)) {
            array_push($this->openAPINullablesSetToNull, 'imageDescription');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('imageDescription', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['imageDescription'] = $imageDescription;

        return $this;
    }

    /**
     * Gets contentSnapshot.
     *
     * @return null|ContentExtractionDescriptor
     */
    public function getContentSnapshot()
    {
        return $this->container['contentSnapshot'];
    }

    /**
     * Sets contentSnapshot.
     *
     * @param null|ContentExtractionDescriptor $contentSnapshot contentSnapshot
     *
     * @return self
     */
    public function setContentSnapshot($contentSnapshot)
    {
        if (is_null($contentSnapshot)) {
            array_push($this->openAPINullablesSetToNull, 'contentSnapshot');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('contentSnapshot', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['contentSnapshot'] = $contentSnapshot;

        return $this;
    }

    /**
     * Gets contentSnapshotDelta.
     *
     * @return null|ContentExtractionDescriptor
     */
    public function getContentSnapshotDelta()
    {
        return $this->container['contentSnapshotDelta'];
    }

    /**
     * Sets contentSnapshotDelta.
     *
     * @param null|ContentExtractionDescriptor $contentSnapshotDelta contentSnapshotDelta
     *
     * @return self
     */
    public function setContentSnapshotDelta($contentSnapshotDelta)
    {
        if (is_null($contentSnapshotDelta)) {
            array_push($this->openAPINullablesSetToNull, 'contentSnapshotDelta');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('contentSnapshotDelta', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['contentSnapshotDelta'] = $contentSnapshotDelta;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
