<?php

/**
 * MonitoringPromptPurposeType.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Sync Core.
 *
 * The Sync Core that sends and receives content from all connected sites and services for Content Sync.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdgeBox\SyncCore\V2\Raw\Model;

/**
 * MonitoringPromptPurposeType Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class MonitoringPromptPurposeType
{
    /**
     * Possible values of this enum.
     */
    public const DISCOVERY = 'discovery';

    public const COMPARISON = 'comparison';

    public const BRAND_PROBE = 'brand-probe';

    public const COMPETITOR_PROBE = 'competitor-probe';

    public const CUSTOM = 'custom';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DISCOVERY,
            self::COMPARISON,
            self::BRAND_PROBE,
            self::COMPETITOR_PROBE,
            self::CUSTOM,
        ];
    }
}
