<?php

/**
 * MonitoringPromptRunEntityVerdictShares.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Sync Core.
 *
 * The Sync Core that sends and receives content from all connected sites and services for Content Sync.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdgeBox\SyncCore\V2\Raw\Model;

use EdgeBox\SyncCore\V2\Raw\ObjectSerializer;

/**
 * MonitoringPromptRunEntityVerdictShares Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class MonitoringPromptRunEntityVerdictShares implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MonitoringPromptRunEntityVerdictShares';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'arguesAgainst' => 'float',
        'caveat' => 'float',
        'neutral' => 'float',
        'favourable' => 'float',
        'recommends' => 'float',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'arguesAgainst' => null,
        'caveat' => null,
        'neutral' => null,
        'favourable' => null,
        'recommends' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'arguesAgainst' => false,
        'caveat' => false,
        'neutral' => false,
        'favourable' => false,
        'recommends' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'arguesAgainst' => 'arguesAgainst',
        'caveat' => 'caveat',
        'neutral' => 'neutral',
        'favourable' => 'favourable',
        'recommends' => 'recommends',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'arguesAgainst' => 'setArguesAgainst',
        'caveat' => 'setCaveat',
        'neutral' => 'setNeutral',
        'favourable' => 'setFavourable',
        'recommends' => 'setRecommends',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'arguesAgainst' => 'getArguesAgainst',
        'caveat' => 'getCaveat',
        'neutral' => 'getNeutral',
        'favourable' => 'getFavourable',
        'recommends' => 'getRecommends',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('arguesAgainst', $data ?? [], null);
        $this->setIfExists('caveat', $data ?? [], null);
        $this->setIfExists('neutral', $data ?? [], null);
        $this->setIfExists('favourable', $data ?? [], null);
        $this->setIfExists('recommends', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (null === $this->container['arguesAgainst']) {
            $invalidProperties[] = "'arguesAgainst' can't be null";
        }
        if (null === $this->container['caveat']) {
            $invalidProperties[] = "'caveat' can't be null";
        }
        if (null === $this->container['neutral']) {
            $invalidProperties[] = "'neutral' can't be null";
        }
        if (null === $this->container['favourable']) {
            $invalidProperties[] = "'favourable' can't be null";
        }
        if (null === $this->container['recommends']) {
            $invalidProperties[] = "'recommends' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets arguesAgainst.
     *
     * @return float
     */
    public function getArguesAgainst()
    {
        return $this->container['arguesAgainst'];
    }

    /**
     * Sets arguesAgainst.
     *
     * @param float $arguesAgainst arguesAgainst
     *
     * @return self
     */
    public function setArguesAgainst($arguesAgainst)
    {
        if (is_null($arguesAgainst)) {
            throw new \InvalidArgumentException('non-nullable arguesAgainst cannot be null');
        }
        $this->container['arguesAgainst'] = $arguesAgainst;

        return $this;
    }

    /**
     * Gets caveat.
     *
     * @return float
     */
    public function getCaveat()
    {
        return $this->container['caveat'];
    }

    /**
     * Sets caveat.
     *
     * @param float $caveat caveat
     *
     * @return self
     */
    public function setCaveat($caveat)
    {
        if (is_null($caveat)) {
            throw new \InvalidArgumentException('non-nullable caveat cannot be null');
        }
        $this->container['caveat'] = $caveat;

        return $this;
    }

    /**
     * Gets neutral.
     *
     * @return float
     */
    public function getNeutral()
    {
        return $this->container['neutral'];
    }

    /**
     * Sets neutral.
     *
     * @param float $neutral neutral
     *
     * @return self
     */
    public function setNeutral($neutral)
    {
        if (is_null($neutral)) {
            throw new \InvalidArgumentException('non-nullable neutral cannot be null');
        }
        $this->container['neutral'] = $neutral;

        return $this;
    }

    /**
     * Gets favourable.
     *
     * @return float
     */
    public function getFavourable()
    {
        return $this->container['favourable'];
    }

    /**
     * Sets favourable.
     *
     * @param float $favourable favourable
     *
     * @return self
     */
    public function setFavourable($favourable)
    {
        if (is_null($favourable)) {
            throw new \InvalidArgumentException('non-nullable favourable cannot be null');
        }
        $this->container['favourable'] = $favourable;

        return $this;
    }

    /**
     * Gets recommends.
     *
     * @return float
     */
    public function getRecommends()
    {
        return $this->container['recommends'];
    }

    /**
     * Sets recommends.
     *
     * @param float $recommends recommends
     *
     * @return self
     */
    public function setRecommends($recommends)
    {
        if (is_null($recommends)) {
            throw new \InvalidArgumentException('non-nullable recommends cannot be null');
        }
        $this->container['recommends'] = $recommends;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
