<?php
/**
 * SyndicationType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EdgeBox\SyncCore\V2\Raw
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cloud Sync Core
 *
 * The Sync Core.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdgeBox\SyncCore\V2\Raw\Model;
use \EdgeBox\SyncCore\V2\Raw\ObjectSerializer;

/**
 * SyndicationType Class Doc Comment
 *
 * @category Class
 * @package  EdgeBox\SyncCore\V2\Raw
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SyndicationType
{
    /**
     * Possible values of this enum
     */
    const SYNDICATE_CREATE_ENTITY = 'syndicate-create-entity';
    const SYNDICATE_DELETE_ENTITY = 'syndicate-delete-entity';
    const PUSH_ENTITY = 'push-entity';
    const DELETE_ENTITY = 'delete-entity';
    const RETRIEVE_FILE = 'retrieve-file';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SYNDICATE_CREATE_ENTITY,
            self::SYNDICATE_DELETE_ENTITY,
            self::PUSH_ENTITY,
            self::DELETE_ENTITY,
            self::RETRIEVE_FILE,
        ];
    }
}


