<?php

/**
 * TaskType.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Sync Core.
 *
 * The Sync Core that sends and receives content from all connected sites and services for Content Sync.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdgeBox\SyncCore\V2\Raw\Model;

/**
 * TaskType Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class TaskType
{
    /**
     * Possible values of this enum.
     */
    public const SYNDICATE_CREATE_ENTITY = 'syndicate-create-entity';

    public const SYNDICATE_DELETE_ENTITY = 'syndicate-delete-entity';

    public const SYNDICATE_UNPUBLISH_ENTITY = 'syndicate-unpublish-entity';

    public const SYNDICATE_DELETE_EMBEDDED_ENTITY = 'syndicate-delete-embedded-entity';

    public const RETRIEVE_ENTITY = 'retrieve-entity';

    public const RETRIEVE_ENTITY_LIST = 'retrieve-entity-list';

    public const PUSH_ENTITY = 'push-entity';

    public const DELETE_ENTITY = 'delete-entity';

    public const DELETE_EMBEDDED_ENTITY = 'delete-embedded-entity';

    public const RETRIEVE_CONFIG = 'retrieve-config';

    public const TRIGGER_WEBHOOK = 'trigger-webhook';

    public const SITEMAP_REQUEST = 'sitemap.request';

    public const ROBOTS_REQUEST = 'robots.request';

    public const CRAWL_PROJECT_TICK = 'crawl.project.tick';

    public const CRAWL_URL = 'crawl.url';

    public const CLASSIFY_CONTENT = 'classify-content';

    public const SCORE_CONTENT = 'score-content';

    public const MONITORING_PROMPT_RUN = 'monitoring-prompt.run';

    public const OPTIMIZE = 'optimize';

    public const OPTIMIZE_REVIEW = 'optimize.review';

    public const ONBOARDING = 'onboarding';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SYNDICATE_CREATE_ENTITY,
            self::SYNDICATE_DELETE_ENTITY,
            self::SYNDICATE_UNPUBLISH_ENTITY,
            self::SYNDICATE_DELETE_EMBEDDED_ENTITY,
            self::RETRIEVE_ENTITY,
            self::RETRIEVE_ENTITY_LIST,
            self::PUSH_ENTITY,
            self::DELETE_ENTITY,
            self::DELETE_EMBEDDED_ENTITY,
            self::RETRIEVE_CONFIG,
            self::TRIGGER_WEBHOOK,
            self::SITEMAP_REQUEST,
            self::ROBOTS_REQUEST,
            self::CRAWL_PROJECT_TICK,
            self::CRAWL_URL,
            self::CLASSIFY_CONTENT,
            self::SCORE_CONTENT,
            self::MONITORING_PROMPT_RUN,
            self::OPTIMIZE,
            self::OPTIMIZE_REVIEW,
            self::ONBOARDING,
        ];
    }
}
