<?php

/**
 * TermAssignment.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Sync Core.
 *
 * The Sync Core that sends and receives content from all connected sites and services for Content Sync.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdgeBox\SyncCore\V2\Raw\Model;

use EdgeBox\SyncCore\V2\Raw\ObjectSerializer;

/**
 * TermAssignment Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class TermAssignment implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TermAssignment';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'taxonomy' => '\EdgeBox\SyncCore\V2\Raw\Model\RuntimeRemoteEntityDependencyWithDependenciesEntity',
        'facet' => 'TaxonomyFacet',
        'term' => '\EdgeBox\SyncCore\V2\Raw\Model\TermAssignmentTerm',
        'source' => '\EdgeBox\SyncCore\V2\Raw\Model\TermAssignmentSource',
        'confidence' => 'float',
        'reasoning' => 'string',
        'filteredByThreshold' => 'float',
        'assignedAt' => 'float',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'taxonomy' => null,
        'facet' => null,
        'term' => null,
        'source' => null,
        'confidence' => null,
        'reasoning' => null,
        'filteredByThreshold' => null,
        'assignedAt' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'taxonomy' => false,
        'facet' => false,
        'term' => false,
        'source' => false,
        'confidence' => true,
        'reasoning' => true,
        'filteredByThreshold' => true,
        'assignedAt' => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'taxonomy' => 'taxonomy',
        'facet' => 'facet',
        'term' => 'term',
        'source' => 'source',
        'confidence' => 'confidence',
        'reasoning' => 'reasoning',
        'filteredByThreshold' => 'filteredByThreshold',
        'assignedAt' => 'assignedAt',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'taxonomy' => 'setTaxonomy',
        'facet' => 'setFacet',
        'term' => 'setTerm',
        'source' => 'setSource',
        'confidence' => 'setConfidence',
        'reasoning' => 'setReasoning',
        'filteredByThreshold' => 'setFilteredByThreshold',
        'assignedAt' => 'setAssignedAt',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'taxonomy' => 'getTaxonomy',
        'facet' => 'getFacet',
        'term' => 'getTerm',
        'source' => 'getSource',
        'confidence' => 'getConfidence',
        'reasoning' => 'getReasoning',
        'filteredByThreshold' => 'getFilteredByThreshold',
        'assignedAt' => 'getAssignedAt',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('taxonomy', $data ?? [], null);
        $this->setIfExists('facet', $data ?? [], null);
        $this->setIfExists('term', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('confidence', $data ?? [], null);
        $this->setIfExists('reasoning', $data ?? [], null);
        $this->setIfExists('filteredByThreshold', $data ?? [], null);
        $this->setIfExists('assignedAt', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (null === $this->container['taxonomy']) {
            $invalidProperties[] = "'taxonomy' can't be null";
        }
        if (null === $this->container['facet']) {
            $invalidProperties[] = "'facet' can't be null";
        }
        if (null === $this->container['term']) {
            $invalidProperties[] = "'term' can't be null";
        }
        if (null === $this->container['source']) {
            $invalidProperties[] = "'source' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets taxonomy.
     *
     * @return RuntimeRemoteEntityDependencyWithDependenciesEntity
     */
    public function getTaxonomy()
    {
        return $this->container['taxonomy'];
    }

    /**
     * Sets taxonomy.
     *
     * @param RuntimeRemoteEntityDependencyWithDependenciesEntity $taxonomy taxonomy
     *
     * @return self
     */
    public function setTaxonomy($taxonomy)
    {
        if (is_null($taxonomy)) {
            throw new \InvalidArgumentException('non-nullable taxonomy cannot be null');
        }
        $this->container['taxonomy'] = $taxonomy;

        return $this;
    }

    /**
     * Gets facet.
     *
     * @return TaxonomyFacet
     */
    public function getFacet()
    {
        return $this->container['facet'];
    }

    /**
     * Sets facet.
     *
     * @param TaxonomyFacet $facet facet
     *
     * @return self
     */
    public function setFacet($facet)
    {
        if (is_null($facet)) {
            throw new \InvalidArgumentException('non-nullable facet cannot be null');
        }
        $this->container['facet'] = $facet;

        return $this;
    }

    /**
     * Gets term.
     *
     * @return TermAssignmentTerm
     */
    public function getTerm()
    {
        return $this->container['term'];
    }

    /**
     * Sets term.
     *
     * @param TermAssignmentTerm $term term
     *
     * @return self
     */
    public function setTerm($term)
    {
        if (is_null($term)) {
            throw new \InvalidArgumentException('non-nullable term cannot be null');
        }
        $this->container['term'] = $term;

        return $this;
    }

    /**
     * Gets source.
     *
     * @return TermAssignmentSource
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source.
     *
     * @param TermAssignmentSource $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets confidence.
     *
     * @return null|float
     */
    public function getConfidence()
    {
        return $this->container['confidence'];
    }

    /**
     * Sets confidence.
     *
     * @param null|float $confidence confidence
     *
     * @return self
     */
    public function setConfidence($confidence)
    {
        if (is_null($confidence)) {
            array_push($this->openAPINullablesSetToNull, 'confidence');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('confidence', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['confidence'] = $confidence;

        return $this;
    }

    /**
     * Gets reasoning.
     *
     * @return null|string
     */
    public function getReasoning()
    {
        return $this->container['reasoning'];
    }

    /**
     * Sets reasoning.
     *
     * @param null|string $reasoning reasoning
     *
     * @return self
     */
    public function setReasoning($reasoning)
    {
        if (is_null($reasoning)) {
            array_push($this->openAPINullablesSetToNull, 'reasoning');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reasoning', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reasoning'] = $reasoning;

        return $this;
    }

    /**
     * Gets filteredByThreshold.
     *
     * @return null|float
     */
    public function getFilteredByThreshold()
    {
        return $this->container['filteredByThreshold'];
    }

    /**
     * Sets filteredByThreshold.
     *
     * @param null|float $filteredByThreshold filteredByThreshold
     *
     * @return self
     */
    public function setFilteredByThreshold($filteredByThreshold)
    {
        if (is_null($filteredByThreshold)) {
            array_push($this->openAPINullablesSetToNull, 'filteredByThreshold');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('filteredByThreshold', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['filteredByThreshold'] = $filteredByThreshold;

        return $this;
    }

    /**
     * Gets assignedAt.
     *
     * @return null|float
     */
    public function getAssignedAt()
    {
        return $this->container['assignedAt'];
    }

    /**
     * Sets assignedAt.
     *
     * @param null|float $assignedAt assignedAt
     *
     * @return self
     */
    public function setAssignedAt($assignedAt)
    {
        if (is_null($assignedAt)) {
            array_push($this->openAPINullablesSetToNull, 'assignedAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('assignedAt', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['assignedAt'] = $assignedAt;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
